---
resources:
    - name: source-code
      type: git
      source:
          uri: https://github.com/warren-sadler/hermes.git
          branch: feat/concourse-build
jobs:
    - name: compile-app
      plan:
          - get: source-code
          - task: install-node-build-deps-and-build
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source:
                        repository: amazonlinux
                inputs:
                    - name: source-code
                outputs:
                    - name: image
                run:
                    path: sh
                    args:
                        - ./source-code/scripts/install-build.sh
# fly -t h set-pipeline -c ./pipelines/test-pipeline.yml -p test-pipeline
